[custom.ada]
command = "echo Ada"
when = """ test -f "*.adb" -o -f "*.ads" """
symbol = "ğŸ›¡ï¸ "
style = "bold green"

[directory]
style = "bold green"
truncation_length = 5

[git_branch]
symbol = "ğŸ”’ "
style = "bold yellow"
