[custom.assembly]
command = "echo ASM"
when = """ test -f "*.asm" -o -f "*.s" """
symbol = "âš™ï¸ "
style = "bold white"

[directory]
style = "bold cyan"
truncation_length = 6

[git_branch]
symbol = "ğŸ”§ "
style = "bold blue"

[memory_usage]
disabled = false
symbol = "ğŸ’¾ "
style = "bold yellow"
