[c]
symbol = "ğŸ”© "
style = "bold red"
detect_extensions = ["c", "h"]

[memory_usage]
disabled = false
symbol = "âš™ï¸ "
style = "bold yellow"

[cmd_duration]
min_time = 50
style = "bold orange"
show_milliseconds = true

[git_branch]
symbol = "ğŸ”— "
style = "bold white"

[directory]
style = "bold white"
truncation_length = 4
