[aws]
symbol = "â˜ï¸ "
style = "bold yellow"

[gcloud]
symbol = "ğŸŒ©ï¸ "
style = "bold blue"

[azure]
symbol = "ğŸŒ€ "
style = "bold cyan"

[kubernetes]
symbol = "âš“ "
style = "bold blue"

[docker_context]
symbol = "ğŸ³ "
style = "bold blue"

[terraform]
symbol = "ğŸ—ï¸ "
style = "bold purple"

[directory]
style = "bold cyan"
truncation_length = 3

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold green"
