[custom.cobol]
command = "echo COBOL"
when = """ test -f "*.cob" -o -f "*.cbl" """
symbol = "ğŸ›ï¸ "
style = "bold green"

[directory]
style = "bold yellow"
truncation_length = 8

[git_branch]
symbol = "ğŸ“Š "
style = "bold green"
