[python]
symbol = "ğŸ "
style = "bold blue"

[rlang]
symbol = "ğŸ“ˆ "
style = "bold blue"

[custom.jupyter]
command = "jupyter --version | head -1"
when = "command -v jupyter"
symbol = "ğŸ““ "
style = "bold orange"

[directory]
style = "bold purple"
truncation_length = 4

[git_branch]
symbol = "ğŸ“Š "
style = "bold green"

[package]
symbol = "ğŸ“¦ "
style = "bold cyan"

[conda]
symbol = "ğŸ…’ "
style = "bold green"
