[custom.database]
command = "echo DBA"
symbol = "ğŸ—„ï¸ "
style = "bold blue"

[directory]
style = "bold cyan"
truncation_length = 4

[custom.mysql]
command = "mysql --version | cut -d' ' -f6"
when = "command -v mysql"
symbol = "ğŸ¬ "
style = "bold blue"

[custom.postgres]
command = "psql --version | cut -d' ' -f3"
when = "command -v psql"
symbol = "ğŸ˜ "
style = "bold blue"

[memory_usage]
disabled = false
symbol = "ğŸ’¾ "
style = "bold yellow"
threshold = 70

[time]
disabled = false
style = "bold white"
time_format = "%H:%M:%S"
