[custom.pascal]
command = "echo Pascal"
when = """ test -f "*.pas" -o -f "*.pp" -o -f "*.dpr" """
symbol = "ğŸ›ï¸ "
style = "bold blue"

[directory]
style = "bold white"
truncation_length = 5

[git_branch]
symbol = "ğŸ”— "
style = "bold cyan"
