[golang]
symbol = "ğŸ¹ "
style = "bold cyan"

[git_branch]
symbol = "ğŸ”— "
style = "bold blue"

[directory]
style = "bold cyan"
truncation_length = 4

[cmd_duration]
min_time = 100
style = "bold green"
show_milliseconds = true

[memory_usage]
disabled = false
symbol = "ğŸš€ "
style = "bold yellow"
