[java]
symbol = "â˜• "
style = "bold red"

[gradle]
symbol = "ğŸ˜ "
style = "bold green"

[maven]
symbol = "ğŸ“‹ "
style = "bold blue"

[spring]
symbol = "ğŸƒ "
style = "bold green"

[directory]
style = "bold yellow"
truncation_length = 4

[git_branch]
symbol = "ğŸŒ³ "
style = "bold green"
