[php]
symbol = "ğŸ˜ "
style = "bold purple"

[composer]
symbol = "ğŸ¼ "
style = "bold blue"

[directory]
style = "bold magenta"
truncation_length = 3

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold green"
