[python]
symbol = "ğŸ "
style = "bold yellow"
pyenv_version_name = true
pyenv_prefix = "pyenv "

[conda]
symbol = "ğŸ…’ "
style = "bold green"

[virtualenv]
symbol = "ğŸ”· "
style = "bold blue"

[package]
symbol = "ğŸ“¦ "
style = "bold cyan"
display_private = true

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold green"

[directory]
style = "bold blue"
truncation_length = 3
