[rust]
symbol = "ğŸ¦€ "
style = "bold red"

[package]
symbol = "ğŸ“¦ "
style = "bold yellow"

[directory]
style = "bold orange"
truncation_length = 4

[git_branch]
symbol = "âš™ï¸ "
style = "bold yellow"

[memory_usage]
disabled = false
symbol = "ğŸ§  "
style = "bold red"
