[custom.sql]
command = "echo SQL"
when = """ test -f "*.sql" """
symbol = "ğŸ—ƒï¸ "
style = "bold blue"

[directory]
style = "bold cyan"
truncation_length = 4

[git_branch]
symbol = "ğŸ“Š "
style = "bold blue"
