[hostname]
ssh_only = false
style = "bold red"
prefix = "ğŸ–¥ï¸ "

[username]
style_user = "bold yellow"
style_root = "bold red"
show_always = true

[directory]
style = "bold blue"
truncation_length = 2
home_symbol = "ğŸ "

[cmd_duration]
min_time = 500
style = "bold yellow"
show_milliseconds = true

[memory_usage]
disabled = false
symbol = "ğŸ§  "
style = "bold red"
threshold = 75

[status]
style = "bold red"
symbol = "âŒ"
success_symbol = "âœ…"
disabled = false

[time]
disabled = false
style = "bold white"
time_format = "%T"
