[custom.vb]
command = "echo VB"
when = """ test -f "*.vb" -o -f "*.vbs" """
symbol = "ğŸ”· "
style = "bold blue"

[directory]
style = "bold blue"
truncation_length = 4

[git_branch]
symbol = "ğŸ“ "
style = "bold cyan"
