format = """
â„ï¸ [$username](bold white)[@](bold cyan)[$hostname](bold blue) â„ï¸
ğŸ§Š [$directory](bold cyan) $git_branch$git_status
â›„ $nodejs$python$rust$docker_context
ğŸŒ¨ï¸ $character"""

[character]
success_symbol = "[â…](bold white)"
error_symbol = "[ğŸ”¥](bold red)"

[git_branch]
format = "[ğŸŒ¿ $branch]($style) "
style = "bold green"

[git_status]
format = '([â„ï¸ $all_status]($style) )'
style = "bold blue"

[nodejs]
format = "[ğŸ§Š $version]($style) "
style = "bold cyan"

[python]
format = '[â›„ $version( \($virtualenv\))]($style) '
style = "bold white"

[docker_context]
format = "[ğŸ‹ $context]($style) "
style = "bold blue"
