format = """
â˜ï¸ [$username](bold white)[@](bold gray)[$hostname](bold light_blue) ğŸŒ¤ï¸
ğŸŒˆ [$directory](bold cyan) $git_branch$git_status
â›… $aws$gcloud$docker_context$kubernetes
ğŸŒ¦ï¸ $character"""

[character]
success_symbol = "[â˜€ï¸](bold yellow)"
error_symbol = "[â›ˆï¸](bold red)"

[git_branch]
format = "[ğŸŒ¿ $branch]($style) "
style = "bold green"

[git_status]
format = '([ğŸŒˆ $all_status]($style) )'
style = "bold blue"

[aws]
format = '[â˜ï¸ $profile( \($region\))]($style) '
style = "bold orange"

[gcloud]
format = '[â˜ï¸ $project( \($region\))]($style) '
style = "bold blue"
