format = """
ğŸŒŒ [$username](bold purple)[@](bold pink)[$hostname](bold magenta) âœ¨
ğŸŒŸ [$directory](bold cyan) $git_branch$git_status
ğŸš€ $nodejs$python$rust$kubernetes
ğŸŒ  $character"""

[character]
success_symbol = "[â­](bold yellow)"
error_symbol = "[ğŸ’¥](bold red)"

[git_branch]
format = "[ğŸŒ™ $branch]($style) "
style = "bold purple"

[git_status]
format = '([ğŸ’« $all_status]($style) )'
style = "bold magenta"

[kubernetes]
format = '[â˜¸ï¸ $context( \($namespace\))]($style) '
style = "bold cyan"
