format = """
ğŸœï¸ [$username](bold yellow)[@](bold orange)[$hostname](bold red) ğŸŒµ
ğŸ¦‚ [$directory](bold brown) $git_branch$git_status
ğŸ”¥ $nodejs$python$rust$cmd_duration
â˜€ï¸ $character"""

[character]
success_symbol = "[ğŸŒŸ](bold yellow)"
error_symbol = "[ğŸ’€](bold red)"

[git_branch]
format = "[ğŸŒµ $branch]($style) "
style = "bold green"

[git_status]
format = '([ğŸ”¥ $all_status]($style) )'
style = "bold red"

[cmd_duration]
format = "[â³ $duration]($style) "
style = "bold orange"
