format = """
ğŸŒ² [$username](bold green)[@](bold brown)[$hostname](bold forest_green) ğŸƒ
ğŸ¦Œ [$directory](bold green) $git_branch$git_status
ğŸ» $nodejs$python$rust$package
ğŸŒ° $character"""

[character]
success_symbol = "[ğŸŒ¿](bold green)"
error_symbol = "[ğŸ”¥](bold red)"

[git_branch]
format = "[ğŸŒ± $branch]($style) "
style = "bold green"

[git_status]
format = '([ğŸ‚ $all_status]($style) )'
style = "bold yellow"

[package]
format = "[ğŸ“¦ $version]($style) "
style = "bold brown"
