tomlformat = "$username$hostname$directory$git_branch$git_status$character"

[username]
format = "[$user](bold white) "
show_always = false

[hostname]
ssh_only = true
format = "@[$hostname](bold blue) "

[directory]
format = "[$path](bold cyan) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch](bold purple) "
symbol = ""

[git_status]
format = '[$all_status$ahead_behind](bold red) '
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸŒ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸŒ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸  Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
