format = """
ğŸŒŠ [$username](bold cyan)[@](bold blue)[$hostname](bold navy) ğŸ‹
ğŸ  [$directory](bold aqua) $git_branch$git_status
ğŸ¦‘ $nodejs$python$rust$docker_context
ğŸ”± $character"""

[character]
success_symbol = "[ğŸŒŠ](bold cyan)"
error_symbol = "[âš¡](bold red)"

[git_branch]
format = "[ğŸŒ¿ $branch]($style) "
style = "bold green"

[git_status]
format = '([ğŸŒŠ $all_status]($style) )'
style = "bold blue"

[docker_context]
format = "[ğŸ³ $context]($style) "
style = "bold cyan"
