format = """
[â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“](bold gray)
[â–“](bold gray) ğŸ”’ USER: [$username](bold green) [â–“](bold gray)
[â–“](bold gray) ğŸ’» HOST: [$hostname](bold yellow) [â–“](bold gray)
[â–“](bold gray) ğŸ“ PATH: [$directory](bold cyan) [â–“](bold gray)
[â–“](bold gray) ğŸŒ¿ $git_branch$git_status [â–“](bold gray)
[â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“](bold gray)
$character"""

[character]
success_symbol = "[â—†](bold green)"
error_symbol = "[â—‡](bold red)"

[git_branch]
format = "BRANCH: [$branch]($style) "
style = "bold purple"

[git_status]
format = 'STATUS: [$all_status]($style) '
style = "bold red"
