format = """
ğŸŒ‹ [$username](bold red)[@](bold orange)[$hostname](bold yellow) ğŸ”¥
ğŸ’ [$directory](bold red) $git_branch$git_status
âš¡ $nodejs$python$rust$cmd_duration
ğŸŒ‹ $character"""

[character]
success_symbol = "[ğŸ”¥](bold orange)"
error_symbol = "[ğŸ’€](bold red)"

[git_branch]
format = "[ğŸŒ¿ $branch]($style) "
style = "bold green"

[git_status]
format = '([âš¡ $all_status]($style) )'
style = "bold red"

[cmd_duration]
format = "[â° $duration]($style) "
style = "bold yellow"
